# Generated by Django 5.1 on 2024-11-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_remove_products_category_companys_products_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companys',
            name='image',
            field=models.FileField(null=True, upload_to='uploads/companys/'),
        ),
    ]
