# Generated by Django 5.1 on 2024-11-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_companys_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorys',
            old_name='des',
            new_name='feature',
        ),
        migrations.RemoveField(
            model_name='categorys',
            name='image',
        ),
    ]
